name: brickit_camera
description: A Flutter plugin for enhanced camera functionalities.
version: 0.0.1
homepage: https://github.com/YOUR_USERNAME/brickit-flutter-camera
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.example.brickit_camera
        pluginClass: BrickitCameraPlugin
      ios:
        pluginClass: BrickitCameraPlugin
