name: camera_android_camerax
description: Android implementation of the camera plugin using the CameraX library.
repository: https://github.com/brickit-app/brickit-flutter-camera/tree/main/camera_android_camerax
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camerax
        pluginClass: CameraAndroidCameraxPlugin
        dartPluginClass: AndroidCameraCameraX

dependencies:
  camera_platform_interface: ^2.2.0
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  stream_transform: ^2.1.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mockito: 5.4.0
  pigeon: ^9.1.0
